FROM registry.access.redhat.com/ubi7/ubi:7.9

ENV INSTALL_DIR=/opt/conjur-api-python3

# Copy below repo file to enable installation of gnome-keyring and dbus-x11
COPY ./CentOS-Linux-AppStream.repo /etc/yum.repos.d/CentOS-Linux-AppStream.repo

RUN yum --disableplugin=subscription-manager -y install -y \
            bash \
            binutils \
            yum-utils \
            gcc gcc-c++ make \
            curl \
            git \
            jq \
            libffi-devel \
            openssl \
            python3 \
            python3-devel \
            python3-pip \
            gnome-keyring \
            dbus-x11 \
            procps \
         && yum --disableplugin=subscription-manager clean all

RUN mkdir -p $INSTALL_DIR
WORKDIR $INSTALL_DIR

COPY ./requirements.txt $INSTALL_DIR/
RUN pip3 install -r requirements.txt

COPY ./bin/build_integrations_tests_runner /build_integrations_tests_runner

COPY . $INSTALL_DIR

COPY ./test/configure_dbus.sh /configure_dbus.sh

#ENTRYPOINT ["./test/configure_dbus.sh"]

