version: '2'
services:
  openssl:
    image: svagi/openssl:latest
    container_name: openssl_test
    entrypoint:
      - openssl
      - req
      - -newkey
      - rsa:2048
      - -days
      - "365"
      - -nodes
      - -x509
      - -config
      - /tmp/conf/tls.conf
      - -extensions
      - v3_ca
      - -keyout
      - /tmp/conf/test_nginx.key
      - -out
      - /tmp/conf/test_nginx.crt
    volumes:
      - ${PWD}/test/test_config/https/:/tmp/conf

  pg:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  conjur:
    image: cyberark/conjur:1.9
    command: server -a dev -f /policy/initial_policy.yml
    environment:
      CONJUR_DATA_KEY: 'OyXV68Mip14xj33huGaQKewmmS+gKtDlp6ECZ2iATpU='
      DATABASE_URL: postgres://postgres@pg/postgres
      RAILS_ENV: development
    ports:
      - 80
    volumes:
      - ${PWD}/test/test_config:/policy:ro
    depends_on:
      - pg

  conjur-https-oss:
    image: nginx:alpine
    ports:
      - 443
    volumes:
      - ${PWD}/test/test_config/https/:/tmp/conf
      - ${PWD}/test/test_config/https/:/etc/nginx/tls/:ro
      - ${PWD}/test/test_config/https/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/test/test_config/https/conjur.conf:/etc/nginx/sites-enabled/conjur.conf:ro
      - ${PWD}/test/test_config/https/dhparams.pem:/etc/nginx/dhparams.pem:ro
    depends_on:
      - conjur

  conjur-cli:
    image: cyberark/conjur-cli:5
    entrypoint: [ "bash", "-c" ]
    command: [ "sleep 999d" ]
    depends_on:
      - conjur
      - conjur-https

  test:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ['sleep', '999d']
    environment:
      CONJUR_AUTHN_API_KEY: Null
      PYTHON_KEYRING_BACKEND: Null
      DEBUG: Null
      TEST_ENV: "True"
    depends_on:
      - conjur
      - conjur-https
    volumes:
      - ${PWD}:/opt/conjur-api-python3

  conjur-https:
    image: registry2.itci.conjur.net/conjur-appliance:5.13.2
    ports:
      - "444:443"
    expose:
      - "443"
      - "444"
      - "1999"
      - "5432"
    security_opt:
        - "seccomp:unconfined"

  test-rhel8:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.test.rhel8
    command: ['sleep', '999d']
    environment:
      CONJUR_AUTHN_API_KEY: Null
      PYTHON_KEYRING_BACKEND: Null
      DEBUG: Null
      TEST_ENV: "True"
      SERVER_MODE: appliance
    depends_on:
      - conjur-https
    volumes:
      - ${PWD}:/opt/conjur-api-python3
