FROM ubuntu:18.04

ENV INSTALL_DIR=/opt/conjur-api-python3

RUN apt-get update && \
    apt-get install -y bash \
                       binutils \
                       build-essential \
                       curl \
                       git \
                       jq \
                       libffi-dev \
                       libssl-dev \
                       python3 \
                       python3-dev \
                       python3-pip

RUN mkdir -p $INSTALL_DIR
WORKDIR $INSTALL_DIR

# Workaround for https://bugs.launchpad.net/usd-importer/+bug/1794041
RUN pip3 install --upgrade keyrings.alt

COPY requirements.txt $INSTALL_DIR/
RUN pip3 install -r requirements.txt

COPY . $INSTALL_DIR
